# Generated by Django 2.1.5 on 2019-08-26 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20190826_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='file1',
        ),
        migrations.RemoveField(
            model_name='article',
            name='file2',
        ),
        migrations.RemoveField(
            model_name='article',
            name='file3',
        ),
        migrations.RemoveField(
            model_name='article',
            name='file4',
        ),
        migrations.RemoveField(
            model_name='article',
            name='file5',
        ),
    ]
