# Generated by Django 2.1.5 on 2019-04-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podstrona',
            name='id',
        ),
        migrations.AlterField(
            model_name='podstrona',
            name='name',
            field=models.CharField(max_length=18, primary_key=True, serialize=False),
        ),
    ]
